language: android
sudo: required # container-based builds only have 4 GB of RAM instead of 7.5 GB

android:
  components:
    - tools
    - tools # specified twice to get latest version
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
   # Clone prebuilt Android NDK for native apps
   - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
   - export ANDROID_NDK_HOME=$HOME/android-ndk-root

script:
   - bash template/gradlew build
   - bash lm75/gradlew build
   - bash hmc5883l/gradlew build
   - bash template-native/gradlew build
   - bash lm75-native/gradlew build
