language: android
sudo: required # container-based builds only have 4 GB of RAM instead of 7.5 GB

android:
  components:
    - tools
    - tools # specified twice to get latest version
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

script:
   - bash template/gradlew build
   - bash lm75/gradlew build
   - bash hmc5883l/gradlew build
